baseURL = 'https://cybercampus-se.github.io/'
languageCode = 'en'
title = 'Royal Hacking Lab'
theme = 'hugo-book'

[params]
    BookLogo = 'logo.png'
    description = 'Welcome to the Royal Hacking Lab. Find information about current research projects and available resources.'

[markup.goldmark.renderer]
    unsafe = true
